In [109]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1,2,3,4,'a'])
print(arr)
print(type(arr))

['1' '2' '3' '4' 'a']
<class 'numpy.ndarray'>


**dimensions**


In [7]:
arr = np.array(33)
print(arr)
# it is 0 D array
# we can also check the dimension of the array
print(arr.ndim)

33
0


In [8]:
arr = np.array([1,2,3,4,5])
print(arr)
# it is 1 D array
print(arr.ndim)

[1 2 3 4 5]
1


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
# it is 2 D array
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [11]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
# it is 3 D array
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [14]:
arr = np.array([[[1,2,3] , [4,5,6] , [7,8,9] , [10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
3


In [30]:
arr = np.array([[1,2,3,4] ,[5,6,7,8]])
print(arr[0][2])
print(arr[1,0])
print(arr[-1,-1])
print(arr[-2,-2])

3
5
8
3


**array indexing**


In [5]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

print(arr[1:5]) # slicing of the array


[1 2 3 4 5]
<class 'numpy.ndarray'>
1
2
3
4
5
[2 3 4 5]


In [4]:
arr = np.array([1,2,3,4])
for i in arr:
  print(i)

1
2
3
4


changing the value by its index

In [3]:
arr = np.array([4,5,8,9,4,0,7,9])
arr[0] = 100
print(arr)


[100   5   8   9   4   0   7   9]


inserting the value

In [ ]:
arr = np.array([4,5,8,9,4,0,7,9])
result = np.insert(arr,5,100)
print(result)


[  4   5   8   9   4 100   0   7   9]


In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
result = np.insert(arr,1,10)
print(result)

[1 2 3 4 5]
[ 1 10  2  3  4  5]


changing the value in dimensional arrays

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
result = np.insert(arr,1,100) # when inserting in the array we can not insert the value in present we have to create a new array then we will insert the new value
print(result)
print(arr)


[  1 100   2   3   4   5   6]
[[1 2 3]
 [4 5 6]]


###arange

In [6]:
arr = np.arange(start = 1 , stop  = 10 , step = 2)
print(arr)

[1 3 5 7 9]


In [5]:
arr = np.arange(4,10)
print(arr)

[4 5 6 7 8 9]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
result = np.insert(arr,0,[10,20,30],axis = 0)
print(result)

[[10 20 30]
 [ 1  2  3]
 [ 4  5  6]]


 **axis**

In [33]:
arr = np.array([[1,2,3,4] , [5,6,7,8]])
result = np.insert(arr, 1,11 ,axis = 0)
print(result)

[[ 1  2  3  4]
 [11 11 11 11]
 [ 5  6  7  8]]


In [52]:
arr = np.array([[1,2,3],[4,5,6]])
result = np.insert(arr,1,11 ,axis =1)
print(result)

[[ 1 11  2  3]
 [ 4 11  5  6]]


In [56]:
arr = np.array([[[1,2,3],[4,5,6]] , [[7,8,9] ,[10,11,12]]])
result = np.insert(arr,1,11,axis = 2)
# print(arr)
print(result)

[[[ 1 11  2  3]
  [ 4 11  5  6]]

 [[ 7 11  8  9]
  [10 11 11 12]]]


In [61]:
arr = np.array([(1,2,3) ,(4,5,6),(7,8,9) ,(10,11,12)])
# print(arr)
result = np.insert(arr,1,11,axis = 1)
print(result)
print(result.size)
print(result.shape)
b = result.reshape(4,4)
print(b)

[[ 1 11  2  3]
 [ 4 11  5  6]
 [ 7 11  8  9]
 [10 11 11 12]]
16
(4, 4)
[[ 1 11  2  3]
 [ 4 11  5  6]
 [ 7 11  8  9]
 [10 11 11 12]]


**reshape the array**

In [66]:
arr = np.array([1,2,3,4,5,6])
b = arr.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [74]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = arr.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [76]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = arr.reshape(2,3,2)
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [78]:
arr = np.array([[[1,2,3] ,[4,5,6]] , [[7,8,9] ,[10,11,12]]])
b = arr.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


auto adjust dimensions


In [102]:
# it can reshape automatically just by giving -1
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = arr.reshape(2,3,-1)
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Basic array operations** and **np.ones**

In [97]:
arr = np.array([1,2])
ones = np.ones(2,dtype = int)
print(arr)
print(ones)
# arr + ones
# arr - ones
# arr * ones
arr/ones
# res = arr + ones
# print(res)

[1 2]
[1 1]


array([1., 2.])

In [105]:
a = np.array([1,2,3,4])
print("sum of array",a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

sum of array 10
1
4
2.5
1.118033988749895


You can sum over the axis of rows with:

In [110]:
b = np.array([[1,2],[3,4]])
print(b.sum(axis = 0)) # sum calculated in column
print(b.sum(axis = 1)) # sum calculated in rows
print(b)


[4 6]
[3 7]
[[1 2]
 [3 4]]


**slicing**

In [132]:
arr = np.array([[1,2,3,4], [5,6,7,8] ,[9,10,11,12]])
# print(arr[0:3 , 1:3])
# print(arr[1,1:4])
print(arr[0:2])
print(arr[0:2,2])

[[1 2 3 4]
 [5 6 7 8]]
[3 7]


In [133]:
x = np.zeros(2)
print(x) # it give the floating value but you can change the datatype by using dtype = datatype


[0. 0.]


In [134]:
x = np.zeros(2 , dtype = int)
print(x)

[0 0]


In [138]:
# we can make the 2d array
x = np.zeros((2,3) , dtype = int)
print(x)

[[0 0 0]
 [0 0 0]]


In [139]:
# we can also make 3d array
y = np.zeros((3,3,3) , dtype = int)
print(y)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [144]:
x = np.zeros(2 , dtype = str)
print(x)

['' '']


In [145]:
x = np.zeros(2 , dtype = "S")
print(x)

[b'' b'']


In [146]:
x = np.zeros(2 , dtype = "i")
print(x)

[0 0]


we can change the data type of array later on or after declared an array


In [147]:
arr = np.array([2.3,3.4,5.6,7.8])
print(arr)
res = arr.astype(int)
print(res)

[2.3 3.4 5.6 7.8]
[2 3 5 7]


broading casting

In [149]:
arr = np.array([2,3])
arr * 1.6
# both the values wiil be divided by the number

array([3.2, 4.8])

**copy**

In [157]:
arr = np.array([1,2,3,4])
newArr = arr.copy() # it is copy in this it will create a new array in this deep copy id done
arr[0] = 100
print(newArr)
print(arr)
print(id(arr))
print(id(newArr))

[1 2 3 4]
[100   2   3   4]
134522953967312
134522953965200


In [156]:
arr = np.array([1,2,3,4])
newArr = arr  # it is called as view
arr[0] = 100
print(newArr)
print(arr)
# the concept is same as in the pyhton copy()
# in this they have same refence

print(id(arr))
print(id(newArr))

[100   2   3   4]
[100   2   3   4]
134522953591440
134522953591440


In [158]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
newArr = arr.copy()
arr[0,0] = 100
print(newArr)
print(arr)


[[1 2 3 4]
 [5 6 7 8]]
[[100   2   3   4]
 [  5   6   7   8]]


In [159]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
newArr = arr
arr[0,0] = 100
print(newArr)
print(arr)

[[100   2   3   4]
 [  5   6   7   8]]
[[100   2   3   4]
 [  5   6   7   8]]


reverse an array


In [160]:
arr = np.array([1,2,3,4,5,6])
res = np.flip(arr)
print(res)

[6 5 4 3 2 1]


In [162]:
arr = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
res = np.flip(arr)
print(res)
print(arr)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


standard deviation

In [163]:
arr= np.array([1,2,3,4,5])
print(np.std(arr))

1.4142135623730951


variance

In [165]:
arr = np.array([1,2,3,4,5])
print(np.var(arr))

2.0
