In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1,2,3,4,'a'])
print(arr)
print(type(arr))

['1' '2' '3' '4' 'a']
<class 'numpy.ndarray'>


dimensions


In [ ]:
arr = np.array(33)
print(arr)
# it is 0 D array

33


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
# it is 1 D array

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
# it is 2 D array

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
# it is 3 D array

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
arr = np.array([1,2,3,4],ndmin=10)
print(arr)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


array indexing


In [ ]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
2
3
4
5


In [ ]:
arr = np.array([1,2,3,4])
for i in arr:
  print(i)

1
2
3
4


changing the value by its index

In [ ]:
arr = np.array([4,5,8,9,4,0,7,9])
arr[0] = 100
print(arr)


[100   5   8   9   4   0   7   9]


inserting the value

In [ ]:
arr = np.array([4,5,8,9,4,0,7,9])
result = np.insert(arr,5,100)
print(result)


[  4   5   8   9   4 100   0   7   9]


changing the value in dimensional arrays

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
result = np.insert(arr,1,100)
print(result)


[  1 100   2   3   4   5   6]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
result = np.insert(arr,0,[10,20,30],axis = 0)
print(result)

[[10 20 30]
 [ 1  2  3]
 [ 4  5  6]]


In [ ]:
arr = np.array([(1,2,3), (4,5,6), (7,8,9), (50,51,52)])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [50 51 52]]
